/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.vista;

/**
 *
 * @author Luli
 */
public class ConfiguracionInicial extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracionInicial
     */
    public ConfiguracionInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre = new javax.swing.JLabel();
        lblApodo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApodo = new javax.swing.JTextField();
        lblApodo1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnombre.setText("Nombre ");
        lblnombre.setName(""); // NOI18N
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        lblnombre.getAccessibleContext().setAccessibleName("lblNombre");

        lblApodo.setText("Tipo:");
        lblApodo.setName(""); // NOI18N
        getContentPane().add(lblApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 140, -1));
        getContentPane().add(txtApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, -1));

        lblApodo1.setText("Apodo");
        lblApodo1.setName(""); // NOI18N
        getContentPane().add(lblApodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heroe", "Villano", " " }));
        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, -1));

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionInicial().setVisible(true);
            }
        });
    }    
    // ====== Getters públicos para que Wiring acceda a los componentes ======
    public javax.swing.JButton getBtnAgregar() { return btnAgregar; }
    public javax.swing.JButton getBtnEliminar() { return btnEliminar; }
    public javax.swing.JComboBox<String> getCmbTipo() { return cmbTipo; }
    public javax.swing.JTextField getTxtNombre1() { return txtNombre; }
    public javax.swing.JTextField getTxtApodo() { return txtApodo; }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel lblApodo;
    private javax.swing.JLabel lblApodo1;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
