package batalla.vista;

import batalla.modelo.ModeloTablaRanking; // Nueva importación
import javax.swing.*;
import java.util.List;

public class VentanaResultadosBatalla extends javax.swing.JFrame {

    // 🔹 Nuevo campo para la tabla de Ranking
    private javax.swing.JTable tablaRanking;

    // ==========================================================
    // 🔹 Constructor
    // ==========================================================
public VentanaResultadosBatalla() {
    initComponents();
    setTitle("🏆 Resultados de la Batalla");

    setSize(600, 500);      
    setLocationRelativeTo(null);  // centrar en pantalla

    btncerrar.addActionListener(e -> dispose());

    // Tabla Ranking
    tablaRanking = new JTable();
    JScrollPane scrollTabla = new JScrollPane(tablaRanking);
    jTabbedPane6.removeAll();
    jTabbedPane6.add(scrollTabla);
}

    // ==========================================================
    // 🔹 Métodos para mostrar información desde el controlador
    // ==========================================================

    /** Muestra el resumen general de la batalla */
    // [Se mantiene este método, aunque no se usa en el nuevo controlador]
    public void mostrarResumen(String texto) {
        //txtResumen.setText(texto);
    }

    /** Muestra las estadísticas detalladas */
    public void mostrarEstadisticas(String texto) {
        txtEstadistica.setText(texto);
    }

    /** Carga el historial de batallas (lista de acciones o resultados) */
    public void mostrarHistorial(List<String> items) {
        DefaultListModel<String> model = new DefaultListModel<>();

        for (String item : items) {
            // Mejora visual simple: cada campo en nueva línea
            String formateado = "<html>" + item.replace(" | ", "<br>") + "</html>";
            model.addElement(formateado);
        }

        JlHistorial.setModel(model);
        JlHistorial.setVisibleRowCount(8);
    }
    
    /** Muestra el ranking de jugadores usando un ModeloTablaRanking */
    public void mostrarRanking(ModeloTablaRanking modelo) {
        if (tablaRanking != null) {
            tablaRanking.setModel(modelo);
        }
    }


    /** Ejemplo de prueba rápida */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            VentanaResultadosBatalla vr = new VentanaResultadosBatalla();
            vr.mostrarResumen("🏁 La batalla terminó en 5 rondas. Ganó el héroe.");
            vr.mostrarEstadisticas("Héroe: 2 victorias\nVillano: 1 victoria");
            vr.mostrarHistorial(java.util.List.of(
                "BATALLA #1 – Héroe: Juan | Villano: Nico | Ganador: Juan | Turnos: 8",
                "BATALLA #2 – Héroe: Ana | Villano: Pepe | Ganador: Pepe | Turnos: 12",
                "BATALLA #3 – Héroe: Lauti | Villano: Fulanito | Ganador: Lauti | Turnos: 6"
            ));
            vr.pack();
            vr.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabsResultados = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        JlHistorial = new javax.swing.JList<>();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEstadistica = new javax.swing.JTextArea();
        btncerrar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        JlHistorial.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(JlHistorial);

        jTabbedPane5.addTab("Batallas", jScrollPane3);

        tabsResultados.addTab("Historial", jTabbedPane5);
        tabsResultados.addTab("Resumen", jTabbedPane6);

        txtEstadistica.setEditable(false);
        txtEstadistica.setColumns(20);
        txtEstadistica.setRows(5);
        jScrollPane2.setViewportView(txtEstadistica);

        jTabbedPane4.addTab("Estadistica", jScrollPane2);

        tabsResultados.addTab("Estadistica", jTabbedPane4);

        getContentPane().add(tabsResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));
        tabsResultados.getAccessibleContext().setAccessibleName("Resumen");

        btncerrar.setText("cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JlHistorial;
    private javax.swing.JButton btncerrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane tabsResultados;
    private javax.swing.JTextArea txtEstadistica;
    // End of variables declaration//GEN-END:variables

}