package batalla.vista;

import javax.swing.*;
import javax.swing.DefaultListModel;
import java.util.List;

public class VentanaResultadosBatalla extends javax.swing.JFrame {

    public VentanaResultadosBatalla() {
        initComponents();
        setTitle("🏆 Resultados de la Batalla");
        setLocationRelativeTo(null);
        btncerrar.addActionListener(e -> dispose());
    }

    // ==========================================================
    // 🔹 Métodos para mostrar información desde el controlador
    // ==========================================================

    /** Muestra el resumen general de la batalla */
    public void mostrarResumen(String texto) {
        txtResumen.setText(texto);
    }

    /** Muestra las estadísticas detalladas */
    public void mostrarEstadisticas(String texto) {
        txtEstadistica.setText(texto);
    }

    /** Carga el historial de batallas (lista de acciones o resultados) */
    public void mostrarHistorial(List<String> items) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String item : items) model.addElement(item);
        JlHistorial.setModel(model);
    }

    /** Ejemplo de prueba rápida */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            VentanaResultadosBatalla vr = new VentanaResultadosBatalla();
            vr.mostrarResumen("🏁 La batalla terminó en 5 rondas. Ganó el héroe.");
            vr.mostrarEstadisticas("Héroe: 2 victorias\nVillano: 1 victoria");
            vr.mostrarHistorial(java.util.List.of(
                "Batalla 1: Héroe venció al villano",
                "Batalla 2: Villano ganó la revancha",
                "Batalla 3: Héroe usó su ataque final y ganó"
            ));
            vr.setVisible(true);
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabsResultados = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEstadistica = new javax.swing.JTextArea();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        JlHistorial = new javax.swing.JList<>();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumen = new javax.swing.JTextArea();
        btncerrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        txtEstadistica.setEditable(false);
        txtEstadistica.setColumns(20);
        txtEstadistica.setRows(5);
        jScrollPane2.setViewportView(txtEstadistica);

        jTabbedPane4.addTab("tab1", jScrollPane2);

        tabsResultados.addTab("Estadistica", jTabbedPane4);

        JlHistorial.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(JlHistorial);

        jTabbedPane5.addTab("tab1", jScrollPane3);

        tabsResultados.addTab("Historial", jTabbedPane5);

        txtResumen.setEditable(false);
        txtResumen.setColumns(20);
        txtResumen.setRows(5);
        jScrollPane1.setViewportView(txtResumen);

        jTabbedPane6.addTab("tab1", jScrollPane1);

        tabsResultados.addTab("Resumen", jTabbedPane6);

        add(tabsResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));
        tabsResultados.getAccessibleContext().setAccessibleName("Resumen");

        btncerrar.setText("cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JlHistorial;
    private javax.swing.JButton btncerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane tabsResultados;
    private javax.swing.JTextArea txtEstadistica;
    private javax.swing.JTextArea txtResumen;
    // End of variables declaration//GEN-END:variables

