/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.vista;

// Getters para que el controlador acceda a los componentes
/**
 *
 * @author Usuario
 */
public class VentanaPrincipalJuego extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalJuego
     */
    public VentanaPrincipalJuego() {
        initComponents();
    }

    public javax.swing.JLabel getLblTurno() {
        return lblturno;
    }

    public javax.swing.JLabel getLblPartida() {
        return lblpartida;
    }

    public javax.swing.JLabel getLblNombreHeroe() {
        return lblNombreHeroe;
    }

    public javax.swing.JLabel getLblApodoHeroe() {
        return lblApodoHeroe;
    }

    public javax.swing.JProgressBar getBarraVidaHeroe() {
        return barraVidaHeroe;
    }

    public javax.swing.JProgressBar getBarraBendicionHeroe() {
        return barraBendicionHeroe;
    }

    public javax.swing.JLabel getLblArmaHeroe() {
        return lblArmaHeroe;
    }

    public javax.swing.JLabel getLblEstadoHeroe() {
        return lblEstadoHeroe;
    }

    public javax.swing.JLabel getLblNombreVillano() {
        return lblNombreVillano;
    }

    public javax.swing.JLabel getLblApodoVillano() {
        return lblApodoVillano;
    }

    public javax.swing.JProgressBar getBarraVidaVillano() {
        return barraVidaVillano;
    }

    public javax.swing.JProgressBar getBarraBendicionVillano() {
        return barraBendicionVillano;
    }

    public javax.swing.JLabel getLblArmaVillano() {
        return lblArmaVillano;
    }

    public javax.swing.JLabel getLblEstadoVillano() {
        return lblEstadoVillano;
    }

    public javax.swing.JTextArea getLogEventos() {
        return jTextArea1;
    }

    public javax.swing.JMenu getMenuPartida() {
        return jMenu1;
    }

    public javax.swing.JMenu getMenuVer() {
        return jMenu2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblturno = new javax.swing.JLabel();
        lblpartida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreVillano = new javax.swing.JLabel();
        lblApodoVillano = new javax.swing.JLabel();
        barraVidaVillano = new javax.swing.JProgressBar();
        barraBendicionVillano = new javax.swing.JProgressBar();
        lblArmaVillano = new javax.swing.JLabel();
        lblEstadoVillano = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNombreHeroe = new javax.swing.JLabel();
        barraVidaHeroe = new javax.swing.JProgressBar();
        barraBendicionHeroe = new javax.swing.JProgressBar();
        lblApodoHeroe = new javax.swing.JLabel();
        lblArmaHeroe = new javax.swing.JLabel();
        lblEstadoHeroe = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel4.setText("Apodo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblturno.setText("Turno");
        getContentPane().add(lblturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 50, 20));

        lblpartida.setText("Partida ");
        getContentPane().add(lblpartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 490, 90));

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, -1));

        lblNombreVillano.setText("Nombre");

        lblApodoVillano.setText("Apodo");

        lblArmaVillano.setText("Arma Equipada");

        lblEstadoVillano.setText("Estado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreVillano)
                            .addComponent(lblApodoVillano))
                        .addContainerGap(170, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblEstadoVillano)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barraVidaVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblArmaVillano)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barraBendicionVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNombreVillano)
                .addGap(18, 18, 18)
                .addComponent(lblApodoVillano)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(barraVidaVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(barraBendicionVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstadoVillano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblArmaVillano)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 220, 200));

        lblNombreHeroe.setText("Nombre");

        lblApodoHeroe.setText("Apodo");

        lblArmaHeroe.setText("Arma Equipada");

        lblEstadoHeroe.setText("Estado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblArmaHeroe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barraBendicionHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombreHeroe)
                    .addComponent(lblApodoHeroe)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblEstadoHeroe)
                        .addGap(58, 58, 58)
                        .addComponent(barraVidaHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNombreHeroe)
                .addGap(18, 18, 18)
                .addComponent(lblApodoHeroe)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraVidaHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoHeroe))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblArmaHeroe)
                    .addComponent(barraBendicionHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 240, 200));

        jMenu1.setText("Partida");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraBendicionHeroe;
    private javax.swing.JProgressBar barraBendicionVillano;
    private javax.swing.JProgressBar barraVidaHeroe;
    private javax.swing.JProgressBar barraVidaVillano;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblApodoHeroe;
    private javax.swing.JLabel lblApodoVillano;
    private javax.swing.JLabel lblArmaHeroe;
    private javax.swing.JLabel lblArmaVillano;
    private javax.swing.JLabel lblEstadoHeroe;
    private javax.swing.JLabel lblEstadoVillano;
    private javax.swing.JLabel lblNombreHeroe;
    private javax.swing.JLabel lblNombreVillano;
    private javax.swing.JLabel lblpartida;
    private javax.swing.JLabel lblturno;
    // End of variables declaration//GEN-END:variables
}
